# -*- coding: utf-8 -*-
"""Simple_Calculator_Using_Gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18--7DZgj6rGRE39Iz5zkaPaLDMTfkYVr
"""

!pip install gradio

import gradio as gr

def add(num1,num2):
 sum = num1+num2
 return sum

i =gr.Interface(fn=add,inputs=["number","number"],outputs="number")
i.launch(debug=True)

